// VIDEO
export const ALL_VIDEOS_LOADED = 'ALL_VIDEOS_LOADED';
export const VIDEO_LOADED = 'VIDEO_LOADED';
export const RELATED_VIDEOS_LOADED = 'RELATED_VIDEOS_LOADED';
export const VIDEO_ERROR = 'VIDEO_ERROR';
